name: task_it
repository: https://github.com/bruc3balo/task_it.git

packages:
  - apps/** # Links taskmanager & taskdoer
  - packages/* # Links core & ui_kit
  - packages/features/** # Links task_board, auth, reports
  - packages/platform/** # Links platform implementations

scripts:
  bootstrap:
    run: melos bootstrap
    description: Link all packages together.

  build:runner:
    run: melos exec --depends-on="build_runner" -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run code generation (such as Freezed/Json) in all packages.